export const TRIAL_CREDITS = 7500;
export const CREDITS_PER_MESSAGE = 1;
export const STANDARD_AUDIENCE_SIZE = 100;
export const SIMULATION_ROUNDS = 10;
export const MAX_MESSAGES_PER_SIMULATION = STANDARD_AUDIENCE_SIZE * SIMULATION_ROUNDS;
